/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author godfr
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
        
        Connection conn = new dbConnect().dbcon();
        PreparedStatement pt = null;
        Statement st;
        Statement st2;
        ResultSet rs;
        ResultSet rs2;
        
        try{
            st = (Statement) conn.createStatement();
            
            int totalPrice = 0;
            
            String sql = "SELECT price FROM totalprice";
            rs = st.executeQuery(sql);
            while(rs.next()) totalPrice = rs.getInt("price");
            
            ArrayList<Integer> countList = new ArrayList<Integer>();
            ArrayList<String> nameList = new ArrayList<String>();
            
            String xettName = "<html>";
            String xettNum = "<html>";
            
            sql = "SELECT * FROM menu";
            rs = st.executeQuery(sql);
            while(rs.next()){
                if(rs.getInt("count") > 0){
                    xettName += rs.getString("menulist")+"<br><br>";   
                    xettNum += rs.getInt("count") + " x &nbsp;" + rs.getInt("price") + "<br><br>";
                }
            }
            
            xettName += "</html>";
            xettNum += "</html>";
            product_name.setText(xettName);
            product_num.setText(xettNum);
            
            double Vat = totalPrice * 7 / 100;
            total.setText(totalPrice + "");
            vatable.setText((totalPrice - Vat) + "");
            vat.setText(Vat + "");
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now(); 
            date.setText("** วันที่ " + now + " **");
        } catch(SQLException ex){
            System.out.println("error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        product_name = new javax.swing.JLabel();
        product_num = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vatable = new javax.swing.JLabel();
        vat = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(380, 600));
        setPreferredSize(new java.awt.Dimension(380, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sarabun", 0, 14)); // NOI18N
        jLabel1.setText("ใบเสร็จรับเงิน ร้านอาหาร");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sarabun", 0, 14)); // NOI18N
        jLabel2.setText("( VAT Included )");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 110, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 1));

        product_name.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        product_name.setText("jLabel3");
        jPanel1.add(product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        product_num.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        product_num.setText("jLabel3");
        jPanel1.add(product_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 330, 1));

        jLabel3.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        jLabel3.setText("รวม");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        total.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        total.setText("jLabel4");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        jLabel4.setText("VATable");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        jLabel5.setText("VAT 7%");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        vatable.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        vatable.setText("jLabel6");
        jPanel1.add(vatable, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        vat.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        vat.setText("jLabel7");
        jPanel1.add(vat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        date.setFont(new java.awt.Font("Sarabun", 0, 12)); // NOI18N
        date.setText("jLabel6");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 10, 550));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 350, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel product_name;
    private javax.swing.JLabel product_num;
    private javax.swing.JLabel total;
    private javax.swing.JLabel vat;
    private javax.swing.JLabel vatable;
    // End of variables declaration//GEN-END:variables
}
