/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.EtchedBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author boatzz
 */
public class Main_page extends javax.swing.JFrame {

    int number = 1;
    int sum = 0;
    int count = 0;
    
    int count_row_sell = 0;
    public Main_page() {
        initComponents();
        centerFrame();
        menu.setVisible(true);
        addmenu.setVisible(false);
        sell.setVisible(false);
        jPanel3.requestFocus(true);
        
        select_addmenu();
        select_menu();
        sales_report();
        initCountSales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void select_addmenu() {
        Connection conn = new dbConnect().dbcon();
        Statement st;
        ResultSet rs;
        try {

            DefaultTableModel dt = (DefaultTableModel) table_menu.getModel();
            dt.setRowCount(0);

            st = (Statement) conn.createStatement();
            String sql = "SELECT * FROM `menu`";
            rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));

                dt.addRow(v);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
        
        //Header column
        JTableHeader theader = table_menu.getTableHeader();
        theader.setBackground(new Color(115,12,22));
        theader.setForeground(Color.white);
        theader.setFont(new Font("Sarabun", Font.PLAIN, 18));
        theader.setBorder(BorderFactory.createBevelBorder(EtchedBorder.RAISED, new Color(115,12,22), new Color(115,12,22)));
        
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        table_menu.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        table_menu.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        table_menu.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        
        table_menu.setRowHeight(30);
        table_menu.setFont(new Font("Sarabun", Font.PLAIN, 16));
    }

    public void select_menu() {
        Connection conn = new dbConnect().dbcon();
        Statement st;
        ResultSet rs;
        try {
            DefaultTableModel dt = (DefaultTableModel) table_manage.getModel();
            dt.setRowCount(0);

            st = (Statement) conn.createStatement();
            String sql = "SELECT * FROM `menu`";
            rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));

                dt.addRow(v);
                count_row_sell++;
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
        
        
        //Header column
        JTableHeader theader = table_manage.getTableHeader();
        theader.setBackground(new Color(115,12,22));
        theader.setForeground(Color.white);
        theader.setFont(new Font("Sarabun", Font.PLAIN, 18));
        theader.setBorder(BorderFactory.createBevelBorder(EtchedBorder.RAISED, new Color(115,12,22), new Color(115,12,22)));
        
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        table_manage.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        table_manage.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        table_manage.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        
        table_manage.setRowHeight(30);
        table_manage.setFont(new Font("Sarabun", Font.PLAIN, 16));
    }

    public void sales_report() {
        Connection conn = new dbConnect().dbcon();
        Statement st;
        ResultSet rs;
        try {

            DefaultTableModel dt = (DefaultTableModel) table_report.getModel();
            dt.setRowCount(0);

            st = (Statement) conn.createStatement();
            String sql = "SELECT * FROM report";
            rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));

                dt.addRow(v);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
        
        //Header column
        JTableHeader theader = table_report.getTableHeader();
        theader.setBackground(new Color(115,12,22));
        theader.setForeground(Color.white);
        theader.setFont(new Font("Sarabun", Font.PLAIN, 18));
        theader.setBorder(BorderFactory.createBevelBorder(EtchedBorder.RAISED, new Color(115,12,22), new Color(115,12,22)));
        
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        table_report.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        table_report.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        table_report.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        
        table_report.setRowHeight(30);
        table_report.setFont(new Font("Sarabun", Font.PLAIN, 16));
    }
    
    public void initCountSales(){
        //Header column
        JTableHeader theader = table_submenu.getTableHeader();
        theader.setBackground(new Color(115,12,22));
        theader.setForeground(Color.white);
        theader.setFont(new Font("Sarabun", Font.PLAIN, 18));
        theader.setBorder(BorderFactory.createBevelBorder(EtchedBorder.RAISED, new Color(115,12,22), new Color(115,12,22)));
        
        DefaultTableModel model_submenu = (DefaultTableModel) table_submenu.getModel();
        model_submenu.setRowCount(0);
       
        for(int i=0;i<count_menu;++i){
            if((int) menu_selected_store[i][1] > 0) model_submenu.addRow(new Object[]{menu_selected_store[i][0], menu_selected_store[i][1]});
        }
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        table_submenu.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        table_submenu.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        
        table_submenu.setRowHeight(30);
        table_submenu.setFont(new Font("Sarabun", Font.PLAIN, 16));
        
        sumprice.setText( "    "+ sum + " B ");
    }
    
    public void centerFrame() {

            Dimension windowSize = getSize();
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Point centerPoint = ge.getCenterPoint();

            int dx = centerPoint.x - windowSize.width / 2;
            int dy = centerPoint.y - windowSize.height / 2;    
            setLocation(dx, dy);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        sell = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_report = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_menu = new javax.swing.JTable();
        pay = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        add = new javax.swing.JButton();
        decrease = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_submenu = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        sumprice = new javax.swing.JTextField();
        addmenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_manage = new javax.swing.JTable();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextmenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tab = new javax.swing.JPanel();
        tabSalesreport = new javax.swing.JButton();
        tabmenu = new javax.swing.JButton();
        tabaddmenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(107, 219, 15));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sell.setBackground(new java.awt.Color(144, 242, 64));
        sell.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_report.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        table_report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "จำนวนรายการ", "ราคารวม", "เวลา"
            }
        ));
        table_report.setFocusable(false);
        table_report.setOpaque(false);
        table_report.setRequestFocusEnabled(false);
        table_report.setRowHeight(30);
        table_report.setShowHorizontalLines(false);
        table_report.setShowVerticalLines(false);
        jScrollPane4.setViewportView(table_report);

        sell.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 880, 480));

        jPanel1.setBackground(new java.awt.Color(77, 153, 11));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Sarabun", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ประวัติการขาย");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 310, 90));

        sell.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 540, 140));

        jPanel3.add(sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 920, 670));

        menu.setBackground(new java.awt.Color(144, 242, 64));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_menu.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        table_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "รหัสเมนู", "ชื่อเมนู", "ราคา"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_menu.setFocusable(false);
        table_menu.setOpaque(false);
        table_menu.setRequestFocusEnabled(false);
        table_menu.setRowHeight(30);
        table_menu.setShowHorizontalLines(false);
        table_menu.setShowVerticalLines(false);
        table_menu.setVerifyInputWhenFocusTarget(false);
        table_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_menuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_menu);

        menu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 500, 580));

        pay.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        menu.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 350, 60));

        cancel.setBackground(new java.awt.Color(77, 153, 11));
        cancel.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("ยกเลิก");
        cancel.setBorderPainted(false);
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        menu.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 90, 40));

        add.setBackground(new java.awt.Color(77, 153, 11));
        add.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("เพิ่ม");
        add.setBorderPainted(false);
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setFocusPainted(false);
        add.setFocusable(false);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        menu.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 90, 40));

        decrease.setBackground(new java.awt.Color(77, 153, 11));
        decrease.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        decrease.setForeground(new java.awt.Color(255, 255, 255));
        decrease.setText("ลด");
        decrease.setBorderPainted(false);
        decrease.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decrease.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decreaseMouseClicked(evt);
            }
        });
        decrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseActionPerformed(evt);
            }
        });
        menu.add(decrease, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 90, 40));

        jLabel5.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel5.setText("ยอดเงินที่ลูกค้าจ่าย");
        menu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 150, 40));

        jLabel6.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("เมนู");
        menu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 50));

        confirm.setBackground(new java.awt.Color(77, 153, 11));
        confirm.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("ยืนยัน");
        confirm.setBorderPainted(false);
        confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });
        menu.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, 120, 50));

        jLabel9.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel9.setText("รายการอาหาร");
        menu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 150, 50));

        table_submenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รายการ", "จำนวน"
            }
        ));
        table_submenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_submenu.setFocusable(false);
        table_submenu.setOpaque(false);
        table_submenu.setRequestFocusEnabled(false);
        table_submenu.setShowHorizontalLines(false);
        table_submenu.setShowVerticalLines(false);
        table_submenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_submenuMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table_submenu);

        menu.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 70, 350, 160));

        jLabel10.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel10.setText("ราคารวม");
        menu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 150, 40));

        sumprice.setEditable(false);
        sumprice.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        sumprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumpriceActionPerformed(evt);
            }
        });
        menu.add(sumprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 350, 60));

        jPanel3.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 920, 670));

        addmenu.setBackground(new java.awt.Color(144, 242, 64));
        addmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_manage.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        table_manage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "รหัสรายการ", "เมนู", "ราคา"
            }
        ));
        table_manage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_manage.setOpaque(false);
        table_manage.setRequestFocusEnabled(false);
        table_manage.setRowHeight(30);
        table_manage.setShowHorizontalLines(false);
        table_manage.setShowVerticalLines(false);
        table_manage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_manageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_manage);

        addmenu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 480, 620));

        Insert.setBackground(new java.awt.Color(77, 153, 11));
        Insert.setFont(new java.awt.Font("Sarabun", 0, 14)); // NOI18N
        Insert.setForeground(new java.awt.Color(255, 255, 255));
        Insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/save.png"))); // NOI18N
        Insert.setText("เพิ่มเมนู");
        Insert.setBorderPainted(false);
        Insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertMouseClicked(evt);
            }
        });
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        addmenu.add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 120, 60));

        Update.setBackground(new java.awt.Color(77, 153, 11));
        Update.setFont(new java.awt.Font("Sarabun", 0, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/update.png"))); // NOI18N
        Update.setText("แก้ไขเมนู");
        Update.setBorderPainted(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        addmenu.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 120, 60));

        delete.setBackground(new java.awt.Color(77, 153, 11));
        delete.setFont(new java.awt.Font("Sarabun", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/delete.png"))); // NOI18N
        delete.setText("ลบเมนู");
        delete.setBorderPainted(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        addmenu.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 120, 60));

        jLabel2.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel2.setText("รหัสเมนู");
        addmenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 72, 50));

        jTextid.setEditable(false);
        jTextid.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jTextid.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        addmenu.add(jTextid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, 50));

        jLabel4.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel4.setText("ราคา");
        addmenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 72, 50));

        jTextmenu.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jTextmenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        addmenu.add(jTextmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 230, 50));

        jLabel3.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel3.setText("ชื่อเมนู");
        addmenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 72, 50));

        jTextprice.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jTextprice.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        addmenu.add(jTextprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 230, 50));

        jLabel7.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ข้อมูล");
        addmenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 90, 40));

        jPanel3.add(addmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 920, 670));

        tab.setBackground(new java.awt.Color(107, 219, 15));
        tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabSalesreport.setBackground(new java.awt.Color(200, 248, 160));
        tabSalesreport.setFont(new java.awt.Font("Sarabun", 1, 20)); // NOI18N
        tabSalesreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/การขาย.png"))); // NOI18N
        tabSalesreport.setText("รายการขาย");
        tabSalesreport.setBorderPainted(false);
        tabSalesreport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabSalesreport.setFocusPainted(false);
        tabSalesreport.setMinimumSize(new java.awt.Dimension(185, 59));
        tabSalesreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabSalesreportActionPerformed(evt);
            }
        });
        tab.add(tabSalesreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 233, 71));

        tabmenu.setBackground(new java.awt.Color(200, 248, 160));
        tabmenu.setFont(new java.awt.Font("Sarabun", 1, 20)); // NOI18N
        tabmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vector60-1296-01.png"))); // NOI18N
        tabmenu.setText(" เมนู            ");
        tabmenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabmenu.setBorderPainted(false);
        tabmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabmenu.setFocusPainted(false);
        tabmenu.setMinimumSize(new java.awt.Dimension(185, 59));
        tabmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabmenuActionPerformed(evt);
            }
        });
        tab.add(tabmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 233, 71));

        tabaddmenu.setBackground(new java.awt.Color(200, 248, 160));
        tabaddmenu.setFont(new java.awt.Font("Sarabun", 1, 20)); // NOI18N
        tabaddmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/insertpng.png"))); // NOI18N
        tabaddmenu.setText(" เพิ่มเมนู    ");
        tabaddmenu.setBorderPainted(false);
        tabaddmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabaddmenu.setFocusPainted(false);
        tabaddmenu.setMinimumSize(new java.awt.Dimension(185, 59));
        tabaddmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabaddmenuMouseClicked(evt);
            }
        });
        tabaddmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabaddmenuActionPerformed(evt);
            }
        });
        tab.add(tabaddmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 233, 71));

        jPanel2.setBackground(new java.awt.Color(26, 55, 6));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ร้านอาหาร.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 275, 160));

        tab.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 160));

        jPanel3.add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 275, 670));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        Connection conn = new dbConnect().dbcon();
        PreparedStatement pt = null;
        try {
            String sql = "INSERT INTO `menu`(menulist, price, count)  VALUES( '" + jTextmenu.getText() + "', '" + jTextprice.getText() + "'  " + ", 0) ";
            pt = conn.prepareStatement(sql);
            pt.execute();
        } catch (SQLException ex) {
            System.out.println("error");
        }
        jTextid.setText(null);
        jTextmenu.setText(null);
        jTextprice.setText(null);
        select_addmenu();
        select_menu();
    }//GEN-LAST:event_InsertActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        Connection conn = new dbConnect().dbcon();
        PreparedStatement pt = null;
        try {
            String sql = "UPDATE `menu` SET `menulist`='" + jTextmenu.getText() + "',`price`='" + jTextprice.getText() + "' WHERE id = '" + jTextid.getText() + "'";
            //UPDATE `menu` SET `menulist`= '" + jTextmenu.getText()  +''',`price`= '" + + "' WHERE `id` = '+ jTextid.getText() + "'
            pt = conn.prepareStatement(sql);
            pt.execute();
        } catch (SQLException ex) {
            System.out.println("error");
        }
        jTextid.setText(null);
        jTextmenu.setText(null);
        jTextprice.setText(null);
        select_addmenu();
        select_menu();
    }//GEN-LAST:event_UpdateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        Connection conn = new dbConnect().dbcon();
        PreparedStatement pt = null;
        try {
            String sql = "DELETE FROM `menu` WHERE  id = '" + jTextid.getText() + "'  ";
            pt = conn.prepareStatement(sql);
            pt.execute();
        } catch (SQLException ex) {
            System.out.print("error");
        }
       jTextid.setText(null);
       jTextmenu.setText(null);
       jTextprice.setText(null);
       select_addmenu();
       select_menu();
    }//GEN-LAST:event_deleteActionPerformed

    private void tabaddmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabaddmenuMouseClicked
       addmenu.setVisible(true);
       menu.setVisible(false);
       sell.setVisible(false);
    }//GEN-LAST:event_tabaddmenuMouseClicked

    private void tabmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabmenuActionPerformed
       addmenu.setVisible(false);
       menu.setVisible(true);
       sell.setVisible(false);
    }//GEN-LAST:event_tabmenuActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payActionPerformed

    private void tabSalesreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabSalesreportActionPerformed
        sell.setVisible(true);
        addmenu.setVisible(false);
        menu.setVisible(false);
    }//GEN-LAST:event_tabSalesreportActionPerformed

    private void tabaddmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabaddmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabaddmenuActionPerformed

    Object[][] menu_selected_store = new Object[200][3];
    int count_menu = 0;
    private void table_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_menuMouseClicked
       //int selected = Integer.parseInt(jTablemenu.getValueAt(jTablemenu.getSelectedRow(), 0).toString());  id 
       String menu_name = table_menu.getValueAt(table_menu.getSelectedRow(), 1).toString();
       int price = Integer.parseInt(table_menu.getValueAt(table_menu.getSelectedRow(), 2).toString());
       sum += price;
       
       if(count_menu==0){
            menu_selected_store[count_menu][0] = menu_name;
            menu_selected_store[count_menu][1] = 1;
            menu_selected_store[count_menu][2] = price;
            count_menu++;
       } else{
            int se = 0;
            for(int i=0;i<count_menu;++i){
                String menu_name_store = (String) menu_selected_store[i][0];
                if(menu_name_store.equals(menu_name)){
                    int count_store = (int) menu_selected_store[i][1];
                    menu_selected_store[i][1] = ++count_store;
                    se = 1;
                    break;
                }
            }
            if(se==0){
                menu_selected_store[count_menu][0] = menu_name;
                menu_selected_store[count_menu][1] = 1;
                menu_selected_store[count_menu][2] = price;
                count_menu++;
            }
       }
       
       initCountSales();
    }//GEN-LAST:event_table_menuMouseClicked

    private void table_manageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_manageMouseClicked
        int selected = Integer.parseInt(table_manage.getValueAt(table_manage.getSelectedRow(), 0).toString());
        String id = (table_manage.getValueAt(table_manage.getSelectedRow(), 0).toString());
        String menu = (table_manage.getValueAt(table_manage.getSelectedRow(), 1).toString());
        String price = (table_manage.getValueAt(table_manage.getSelectedRow(), 2).toString());
        jTextid.setText(String.valueOf(id));
        jTextmenu.setText(menu);
        jTextprice.setText(price);
    }//GEN-LAST:event_table_manageMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

    }//GEN-LAST:event_cancelActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        int price_store = (int) menu_selected_store[row_submenu_focus][2];
        int count_store = (int) menu_selected_store[row_submenu_focus][1];
        sum -= price_store * count_store;
        menu_selected_store[row_submenu_focus][1] = 0;
        initCountSales();
    }//GEN-LAST:event_cancelMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       
    }//GEN-LAST:event_addActionPerformed

    private void decreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseActionPerformed
           
    }//GEN-LAST:event_decreaseActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        int count_store = (int) menu_selected_store[row_submenu_focus][1];
        menu_selected_store[row_submenu_focus][1] = ++count_store;
        sum += (int) menu_selected_store[row_submenu_focus][2];
        initCountSales();
    }//GEN-LAST:event_addMouseClicked

    private void decreaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decreaseMouseClicked
        int count_store = (int) menu_selected_store[row_submenu_focus][1];
        menu_selected_store[row_submenu_focus][1] = --count_store;
        sum -= (int) menu_selected_store[row_submenu_focus][2];
        initCountSales();
    }//GEN-LAST:event_decreaseMouseClicked

    private void InsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertMouseClicked

    int row_submenu_focus = -1;
    private void table_submenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_submenuMouseClicked
        row_submenu_focus = table_submenu.getSelectedRow();
    }//GEN-LAST:event_table_submenuMouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        Connection conn = new dbConnect().dbcon();
        PreparedStatement pt = null;
        Statement st;
        ResultSet rs;
        
        try {
            String sql = "UPDATE totalPrice SET price=" + sum + ", paid=" + Integer.parseInt(pay.getText()) + " WHERE 1=1";
            pt = conn.prepareStatement(sql);
            pt.execute();
            sum = 0;
            
            sql = "UPDATE menu SET count=0 WHERE 1=1";
            pt = conn.prepareStatement(sql);
            pt.execute();
            
            for(int i=0;i<count_menu;++i){
                int count_store = (int) menu_selected_store[i][1];
                String menu_store = (String) menu_selected_store[i][0];
                
                sql = "UPDATE menu SET count=" + count_store + " WHERE menulist='" + menu_store + "'";
                pt = conn.prepareStatement(sql);
                pt.execute();
                
                menu_selected_store[i][0] = "";
                menu_selected_store[i][1] = 0;
                menu_selected_store[i][2] = 0;
            }
            
            int sum_count = 0;
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now(); 
            
            st = (Statement) conn.createStatement();
            sql = "SELECT count FROM menu WHERE count>0";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                sum_count += rs.getInt("count");
            }
            st = (Statement) conn.createStatement();
            sql = "SELECT price FROM totalprice";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                sql = "INSERT INTO report (count_menu, price, date) VALUES ("+sum_count+", "+rs.getInt("price")+", '"+now+"')";
                pt = conn.prepareStatement(sql);
                pt.execute();
            }

            pay.setText("");
            count_menu = 0;
            new receip().setVisible(true);
            initCountSales();
            sales_report();
        } catch (SQLException ex) {
            System.out.print("error");
        }
    }//GEN-LAST:event_confirmMouseClicked

    private void sumpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumpriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insert;
    private javax.swing.JButton Update;
    private javax.swing.JButton add;
    private javax.swing.JPanel addmenu;
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JButton decrease;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextid;
    private javax.swing.JTextField jTextmenu;
    private javax.swing.JTextField jTextprice;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField pay;
    private javax.swing.JPanel sell;
    private javax.swing.JTextField sumprice;
    private javax.swing.JPanel tab;
    private javax.swing.JButton tabSalesreport;
    private javax.swing.JButton tabaddmenu;
    private javax.swing.JTable table_manage;
    private javax.swing.JTable table_menu;
    private javax.swing.JTable table_report;
    private javax.swing.JTable table_submenu;
    private javax.swing.JButton tabmenu;
    // End of variables declaration//GEN-END:variables
}
